### ISSUE TITLE
過去の記事をふたたび通知してしまうことがある

### ISSUE THREAD

**Issue by kotofurumiya** [kotofurumiya/gbf_news_notifier_bot#1]
原因わかんね。そのうち調べる

**Comment by kotofurumiya** [comment]
これ、原因のひとつ？エラーハンドリングろくにしてないからな

この辺： https://github.com/discordjs/discord.js/issues/2523

```
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
    at Client.emit (events.js:177:17)
    at WebSocketConnection.onError (/opt/gbf_notifier_bot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:374:17)
    at WebSocket.onError (/opt/gbf_notifier_bot/node_modules/discord.js/node_modules/ws/lib/event-target.js:128:16)
    at WebSocket.emit (events.js:188:13)
    at _receiver.cleanup (/opt/gbf_notifier_bot/node_modules/discord.js/node_modules/ws/lib/websocket.js:211:14)
    at Receiver.cleanup (/opt/gbf_notifier_bot/node_modules/discord.js/node_modules/ws/lib/receiver.js:557:13)
    at WebSocket.finalize (/opt/gbf_notifier_bot/node_modules/discord.js/node_modules/ws/lib/websocket.js:206:20)
    at TLSSocket.emit (events.js:188:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
```

**Comment by kotofurumiya** [comment]
直した、はず。もうちょっと様子見

**Comment by kotofurumiya** [comment]
特に問題なさそうな気がするので一旦閉める
